#!/bin/bash

# Assumes, that you have installed qt5 via MXE.

MXE_QT5_QMAKE=~/mxe/usr/i686-pc-mingw32/qt5/bin/qmake
ZIP=zip
UNIX2DOS=unix2dos
VERSION=0.1.1

# Build

$MXE_QT5_QMAKE && make || exit -1

# Install to packaging dir

CREATE_PACKAGE_PATH=snm-$VERSION-windows-x86-qt5
rm -rf $CREATE_PACKAGE_PATH
mkdir $CREATE_PACKAGE_PATH

cp -v ./release/snm.exe $CREATE_PACKAGE_PATH

TEXT_FILES="AUTHORS CHANGELOG COPYING README"
cp -v $TEXT_FILES $CREATE_PACKAGE_PATH
cd $CREATE_PACKAGE_PATH
$UNIX2DOS $TEXT_FILES
cd ..

# Create zip archive

ZIP_ARCHIVE=$CREATE_PACKAGE_PATH.zip
rm -f $ZIP_ARCHIVE
$ZIP -rv $ZIP_ARCHIVE $CREATE_PACKAGE_PATH

ls -ltr

echo "Done."

