#!/bin/bash

# Assumes, that you have 64-bit (static) qt5 libs installed in ~/qt5.

QT5_QMAKE=~/qt5/bin/qmake
TAR=tar
VERSION=1.0.0

# Build

$QT5_QMAKE && make || exit -1

# Install to packaging dir

CREATE_PACKAGE_PATH=snm-$VERSION-linux-x86_64-qt5
rm -rf $CREATE_PACKAGE_PATH
mkdir $CREATE_PACKAGE_PATH

cp -v ./snm $CREATE_PACKAGE_PATH

TEXT_FILES="AUTHORS CHANGELOG COPYING README"
cp -v $TEXT_FILES $CREATE_PACKAGE_PATH
cd $CREATE_PACKAGE_PATH
cd ..

# Create zip archive
TGZ_ARCHIVE=$CREATE_PACKAGE_PATH.tar.gz
rm -f $TGZ_ARCHIVE
$TAR czvf $TGZ_ARCHIVE $CREATE_PACKAGE_PATH

ls -ltr

echo "Done."

